"""Build the "More work" card grid in case-studies.html from ContentSource.

Self-contained (stdlib only) and idempotent: re-running rewrites everything
between the work:start / work:end markers from the markdown rather than
editing it in place, so 40+ cards never drift out of sync with the source.

    python buildwork.py
"""
import html
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "ContentSource", "alpha-squared-site-content.md")
PAGE = os.path.join(HERE, "case-studies.html")
IMG_DIR = os.path.join(HERE, "assets", "CaseStudies")
IMG_HREF = "assets/CaseStudies"

START = "<!-- work:start \u2014 generated by buildwork.py, do not edit by hand -->"
END = "<!-- work:end -->"

# Already written up in full further up the page.
SKIP = {"Fluidsdata", "Alliance Driveaway Solutions"}

# Section 2 either omits a category or gives one too long for the badge, and
# a couple are mislabelled in the deck the markdown was extracted from.
BADGE = {
    "Oravia": "Travel &amp; Tourism",
    "Amwalouna": "Real Estate",
    "Compo++": "Energy &amp; Industrial",
    "Repair Beat": "SaaS / POS",
    "FoodStretcher Plus &amp; OCR": "Fintech",
    "Kingsland": "Real Estate",
    "Who I Follow": "Sports Tech",
}

SENTENCE = re.compile(r"(?<=[.!?])\s+(?=[A-Z])")


def two_sentences(text):
    """Cards get a one-liner; the long-form copy stays in the markdown."""
    parts = SENTENCE.split(" ".join(text.split()))
    out = " ".join(parts[:2]).strip()
    return out if out.endswith((".", "!", "?")) else out + "."


def esc(text):
    # Text content and quote-free attribute values only, so ' stays readable.
    return html.escape(text, quote=False)


def parse_featured(block):
    """Section 2 - '### Name - Subtitle', an image line, then prose."""
    projects = []
    for chunk in re.split(r"^### ", block, flags=re.M)[1:]:
        lines = chunk.strip().splitlines()
        heading = lines[0].strip()
        name, _, subtitle = heading.partition("\u2014")

        image, desc, category = None, [], None
        for line in lines[1:]:
            line = line.strip()
            if line.startswith("**Image:**"):
                found = re.search(r"`([^`]+)`", line)
                image = found.group(1) if found else None
            elif line.startswith("**Category:**"):
                category = line.split("**Category:**", 1)[1].strip()
            elif line.startswith("**"):
                continue  # **Tech:** and friends
            elif line:
                desc.append(line)

        projects.append({
            "name": esc(name.strip()),
            "category": esc(category or subtitle.strip()),
            "desc": esc(two_sentences(" ".join(desc))),
            "image": image,
        })
    return projects


def parse_table(block):
    """Section 3 - | Project | Description | Category | Image |."""
    projects = []
    for line in block.splitlines():
        line = line.strip()
        if not line.startswith("|") or line.startswith("|---"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) != 4 or cells[0] == "Project":
            continue
        name, desc, category, images = cells
        found = re.search(r"`([^`]+)`", images)
        projects.append({
            "name": esc(name),
            "category": esc(category),
            "desc": esc(two_sentences(desc)),
            "image": found.group(1) if found else None,
        })
    return projects


CARD = """      <article class="work" data-anim="up"{delay}>
        <div class="work__shot">
          <img src="{href}/{image}" alt="{alt}" loading="lazy" decoding="async" />
        </div>
        <div class="work__body">
          <span class="badge">{category}</span>
          <h3>{name}</h3>
          <p>{desc}</p>
        </div>
      </article>"""


def render(projects):
    cards = []
    for i, p in enumerate(projects):
        column = i % 3
        cards.append(CARD.format(
            delay="" if column == 0 else ' data-delay="%.2f"' % (0.08 * column),
            href=IMG_HREF,
            image=p["image"],
            alt="%s screenshot" % p["name"],
            category=p["category"],
            name=p["name"],
            desc=p["desc"],
        ))
    return "\n\n".join(cards)


def main():
    with open(SRC, encoding="utf-8") as fh:
        md = fh.read()

    featured = md.split("## 2.", 1)[1].split("## 3.", 1)[0]
    archive = md.split("## 3.", 1)[1].split("**Company/branding", 1)[0]

    projects = parse_featured(featured) + parse_table(archive)

    kept = []
    for p in projects:
        if p["name"] in SKIP:
            continue
        if not p["image"]:
            print("no image, skipping:", p["name"])
            continue
        if not os.path.exists(os.path.join(IMG_DIR, p["image"])):
            print("missing file, skipping:", p["image"])
            continue
        p["category"] = BADGE.get(p["name"], p["category"])
        kept.append(p)

    with open(PAGE, encoding="utf-8") as fh:
        page = fh.read()

    if START not in page or END not in page:
        raise SystemExit("markers not found in case-studies.html")

    block = "%s\n%s\n      %s" % (START, render(kept), END)
    page = re.sub(
        re.escape(START) + r".*?" + re.escape(END), lambda _: block, page, flags=re.S)

    with open(PAGE, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(page)

    print("wrote %d cards to case-studies.html" % len(kept))


if __name__ == "__main__":
    main()
