"""Generate the individual case study pages, the index grid and sitemap.xml.

Replaces buildwork.py. Stdlib only, idempotent: every run rewrites the pages
in case-studies/ from casedata.py and rewrites case-studies.html between the
work:start / work:end markers, so 45 cards and 48 detail pages never drift.

    python buildcases.py              # from casedata.py
    python buildcases.py --from-json  # from data/case-studies.json

--from-json builds from the same export that seeds MongoDB, which is how a
record edited in the database gets proven against the generated pages.

Flagship projects (casedata.FLAGSHIP) are hand-authored and are not overwritten
here, but they still get index cards, prev/next links and sitemap entries.
"""
import datetime
import html
import json
import os
import re
import sys

import casedata

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "case-studies")
IMG_DIR = os.path.join(HERE, "assets", "CaseStudies")
INDEX = os.path.join(HERE, "case-studies.html")
SITEMAP = os.path.join(HERE, "sitemap.xml")
EXPORT = os.path.join(HERE, "data", "case-studies.json")

SITE = "https://alphasquared.ca"
IMG_HREF = "assets/CaseStudies"

START = "<!-- work:start \u2014 generated by buildcases.py, do not edit by hand -->"
END = "<!-- work:end -->"

# Top-level pages that also belong in the sitemap, with their change weight.
STATIC_PAGES = [
    ("index.html", "1.0"), ("trucking.html", "0.9"), ("services.html", "0.9"),
    ("case-studies.html", "0.9"), ("about.html", "0.8"), ("contact.html", "0.8"),
    ("trust.html", "0.6"),
]


def esc(t):
    return html.escape(t, quote=False)


def attr(t):
    return html.escape(t, quote=True)


# ─────────────────────────────── shared shell ────────────────────────────────

HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{title}</title>
<meta name="description" content="{description}" />
<link rel="canonical" href="{url}" />

<meta property="og:type" content="article" />
<meta property="og:site_name" content="Alpha Squared" />
<meta property="og:title" content="{title}" />
<meta property="og:description" content="{description}" />
<meta property="og:url" content="{url}" />
<meta property="og:image" content="{ogimage}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{title}" />
<meta name="twitter:description" content="{description}" />
<meta name="twitter:image" content="{ogimage}" />

<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="../css/style.css?v=20260813c" />
<link rel="stylesheet" href="../css/theme.css?v=20260813c" />
<link rel="stylesheet" href="../css/case.css?v=20260813c" />
<link rel="stylesheet" href="../css/chatbot.css?v=20260813c" />

<!-- Theme is resolved before first paint so a light-mode reload never flashes dark.
     Braces are doubled because this template goes through str.format. -->
<script>(function(){{try{{var m=localStorage.getItem('a2-theme')||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');if(m==='light')document.documentElement.setAttribute('data-theme','light');}}catch(e){{}}}})();</script>

<script type="application/ld+json">
{jsonld}
</script>
</head>

<body>

<header class="nav" id="nav">
  <div class="nav__inner">
    <a href="../index.html" class="brand" aria-label="Alpha Squared home, ideas implemented">
      <img src="../assets/logo-full.png" alt="Alpha Squared logo" class="brand__logo" />
    </a>

    <nav class="nav__links">
      <a href="../trucking.html">Trucking &amp; Transport</a>
      <a href="../services.html">Services</a>
      <a href="../case-studies.html" class="is-active">Case Studies</a>
      <a href="../about.html">About Us</a>
    </nav>

    <a href="../contact.html" class="btn nav__cta"><span>Contact</span></a>

    <button class="nav__burger" id="burger" aria-label="Menu" aria-expanded="false">
      <span></span><span></span><span></span>
    </button>
  </div>
</header>

<main>
"""

FOOT = """
</main>

<footer class="footer">
  <div class="wrap">

    <div class="footer__grid">
      <div class="footer__brand">
        <a href="../index.html" class="brand" aria-label="Alpha Squared home, ideas implemented">
          <img src="../assets/logo-full-white.png" alt="Alpha Squared logo" class="brand__logo" />
        </a>
        <p>Canadian software studio building for operators and enterprises since 2012.
          Edmonton, Alberta. Trucking and transport specialists. Ideas implemented.</p>

        <h2 class="footer__h footer__h--soc">Follow Along</h2>
        <!-- Profile URLs are placeholders until the real handles are confirmed;
             WhatsApp and email are live. -->
        <ul class="soc">
          <li><a href="#" aria-label="Alpha Squared on LinkedIn">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4.98 3.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5ZM3 9.5h4V21H3V9.5Zm6.5 0h3.8v1.6h.05a4.2 4.2 0 0 1 3.77-2.07c4.03 0 4.78 2.65 4.78 6.1V21h-4v-5.1c0-1.22-.02-2.78-1.7-2.78-1.7 0-1.96 1.33-1.96 2.7V21h-4V9.5Z"/></svg>
          </a></li>
          <li><a href="#" aria-label="Alpha Squared on X">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M17.53 3h3.2l-6.99 7.99L22 21h-6.44l-5.04-6.6L4.75 21H1.54l7.48-8.55L2 3h6.6l4.56 6.03L17.53 3Zm-1.12 16.06h1.77L7.67 4.84H5.77l10.64 14.22Z"/></svg>
          </a></li>
          <li><a href="#" aria-label="Alpha Squared on Facebook">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.5 21v-8h2.7l.4-3.1h-3.1V7.9c0-.9.25-1.5 1.54-1.5h1.66V3.63A22 22 0 0 0 14.3 3.5c-2.4 0-4.05 1.47-4.05 4.17V9.9H7.5V13h2.75v8h3.25Z"/></svg>
          </a></li>
          <li><a href="#" aria-label="Alpha Squared on Instagram">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.3" cy="6.7" r="1.1" fill="currentColor" stroke="none"/></svg>
          </a></li>
          <li><a href="https://wa.me/18259772020" target="_blank" rel="noopener" aria-label="Alpha Squared on WhatsApp">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12.04 2C6.6 2 2.2 6.4 2.2 11.84c0 1.74.46 3.44 1.32 4.94L2 22l5.34-1.4a9.8 9.8 0 0 0 4.7 1.2h.01c5.43 0 9.84-4.4 9.84-9.84C21.89 6.4 17.48 2 12.04 2Zm5.76 14.02c-.24.68-1.4 1.3-1.94 1.34-.5.05-.98.23-3.3-.69-2.78-1.1-4.55-3.94-4.69-4.13-.13-.19-1.12-1.49-1.12-2.84s.71-2.01.96-2.29c.25-.27.55-.34.73-.34l.53.01c.17 0 .4-.06.62.48.24.57.8 1.97.87 2.11.07.14.12.31.02.5-.09.19-.14.31-.28.47l-.42.49c-.14.14-.28.29-.12.57.16.27.71 1.17 1.52 1.9 1.05.93 1.93 1.22 2.2 1.36.28.14.44.12.6-.07.17-.19.7-.81.88-1.09.19-.27.37-.23.63-.14.25.1 1.65.78 1.93.92.28.14.47.21.54.33.07.11.07.65-.17 1.33Z"/></svg>
          </a></li>
          <li><a href="mailto:info@alphasquared.co" aria-label="Email Alpha Squared">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="2.5" y="4.5" width="19" height="15" rx="2.5"/><path d="m3.5 7 8.5 6 8.5-6"/></svg>
          </a></li>
        </ul>
      </div>

      <div>
        <h2 class="footer__h">Solutions</h2>
        <ul>
          <li><a href="../trucking.html">Trucking &amp; Transport</a></li>
          <li><a href="../services.html#platforms">Operations Platforms</a></li>
          <li><a href="../services.html#mobile">Mobile Apps</a></li>
          <li><a href="../services.html#ai">AI &amp; Automation</a></li>
          <li><a href="../services.html#teams">Dedicated Teams</a></li>
        </ul>
      </div>

      <div>
        <h2 class="footer__h">Company</h2>
        <ul>
          <li><a href="../about.html">About Us</a></li>
          <li><a href="../case-studies.html">Case Studies</a></li>
          <li><a href="../services.html">Services</a></li>
          <li><a href="../trust.html">Trust &amp; Security</a></li>
          <li><a href="../contact.html">Contact</a></li>
        </ul>
      </div>

      <div>
        <h2 class="footer__h">Talk to Us</h2>
        <ul class="footer__contact">
          <li><span>Phone</span><a href="tel:+18259772020">+1 (825) 977-2020</a></li>
          <li><span>Email</span><a href="mailto:info@alphasquared.co">info@alphasquared.co</a></li>
          <li><span>Office</span>5479 CrabApple Loop SW<br />Edmonton, Alberta T6X 1S5</li>
          <li><span>Hours</span>Mountain Time, 8am to 6pm</li>
        </ul>
      </div>
    </div>

    <div class="footer__base">
      <span>© 2026 Alpha Squared. Ideas Implemented.</span>
      <ul class="footer__legal">
        <li><a href="../sitemap.xml">Sitemap</a></li>
      </ul>
      <span>Built in Edmonton, Alberta</span>
    </div>
  </div>
</footer>

{chatbot}

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/CustomEase.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/lenis@1.1.14/dist/lenis.min.js"></script>
<script src="https://unpkg.com/split-type@0.3.4/umd/index.min.js"></script>
<script src="../js/main.js?v=20260813c"></script>
<script src="../js/case.js?v=20260813c"></script>
<script src="../js/chatbot.js?v=20260813c"></script>
</body>
</html>
"""

CHATBOT = """<!-- Ask Alpha2 chat widget. Markup is duplicated per page on purpose:
     this is a static site with no include step. Source of truth for the copy
     is chatbot-widget/chatbot-snippet.html. -->
<button id="askA2-launcher" aria-label="Open chat">
  <div class="askA2-ring"></div>
  <svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/></svg>
  <div class="askA2-badge-dot" id="askA2-badge-dot">1</div>
</button>

<div id="askA2-panel">
  <div class="askA2-head">
    <div class="askA2-avatar">&#945;&sup2;</div>
    <div>
      <div class="askA2-title">Ask Alpha&sup2;</div>
      <div class="askA2-status"><span class="askA2-status-dot"></span>Usually replies instantly</div>
    </div>
    <button class="askA2-close" id="askA2-close" aria-label="Close chat">
      <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M18 6L6 18M6 6l12 12"/></svg>
    </button>
  </div>

  <div class="askA2-body" id="askA2-body">
    <div class="askA2-msg bot">Hey. I'm the Alpha&sup2; assistant. Ask me about our work, pricing, timelines or how we staff a project, or tap a question below.</div>
  </div>

  <div class="askA2-quick-wrap">
    <div class="askA2-quick-label">Quick questions</div>
    <div class="askA2-quick-row" id="askA2-quick-row">
      <button class="askA2-quick-btn" data-q="What services do you offer?">What services do you offer?</button>
      <button class="askA2-quick-btn" data-q="Tell me about your AI automation work">Tell me about AI automation</button>
      <button class="askA2-quick-btn" data-q="What does a project cost?">What does a project cost?</button>
      <button class="askA2-quick-btn" data-q="How do I book a call?">How do I book a call?</button>
    </div>
  </div>

  <div class="askA2-input-row">
    <input type="text" id="askA2-input" placeholder="Ask anything..." aria-label="Ask a question" />
    <button class="askA2-send" id="askA2-send" aria-label="Send">
      <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 2 11 13M22 2l-7 20-4-9-9-4 20-7z"/></svg>
    </button>
  </div>

  <div class="askA2-disclaimer">Ask Alpha&sup2; can make mistakes. For anything important, book a call with our team.</div>
</div>"""


# ───────────────────────────── interactive modules ───────────────────────────

def ix_flow(ix):
    tabs, panes = [], []
    for i, s in enumerate(ix["steps"]):
        on = " is-on" if i == 0 else ""
        tabs.append(
            '        <button class="ix__step%s" data-ix-tab="%d" type="button">'
            '<span class="ix__step-k">%s</span><span class="ix__step-t">%s</span></button>'
            % (on, i, esc(s["k"]), esc(s["t"])))
        panes.append(
            '        <div class="ix__pane%s" data-ix-pane="%d"><h3>%s</h3><p>%s</p></div>'
            % (on, i, esc(s["t"]), esc(s["d"])))
    return ('      <div class="ix__steps" role="tablist">\n%s\n      </div>\n'
            '      <div class="ix__panes">\n%s\n      </div>'
            % ("\n".join(tabs), "\n".join(panes)))


def ix_screens(ix):
    tabs, panes = [], []
    for i, s in enumerate(ix["shots"]):
        on = " is-on" if i == 0 else ""
        tabs.append('        <button class="ix__tab%s" data-ix-tab="%d" type="button">%s</button>'
                    % (on, i, esc(s["t"])))
        panes.append(
            '        <figure class="ix__pane%s" data-ix-pane="%d">\n'
            '          <img src="../%s/%s" alt="%s" loading="lazy" decoding="async" />\n'
            '          <figcaption>%s</figcaption>\n        </figure>'
            % (on, i, IMG_HREF, s["img"], attr(s["alt"]), esc(s["cap"])))
    return ('      <div class="ix__tabs" role="tablist">\n%s\n      </div>\n'
            '      <div class="ix__panes ix__panes--shots">\n%s\n      </div>'
            % ("\n".join(tabs), "\n".join(panes)))


def ix_metrics(ix):
    rows = []
    for m in ix["items"]:
        rows.append(
            '        <div class="ix__meter" style="--p:%s">\n'
            '          <div class="ix__meter-n" data-count="%s" data-suffix="%s">0%s</div>\n'
            '          <div class="ix__meter-l">%s</div>\n'
            '          <div class="ix__meter-bar"><i></i></div>\n        </div>'
            % (m["p"], m["n"], attr(m["suffix"]), esc(m["suffix"]), esc(m["l"])))
    return '      <div class="ix__meters">\n%s\n      </div>' % "\n".join(rows)


def ix_stack(ix):
    rows = []
    for i, l in enumerate(ix["layers"]):
        on = " is-on" if i == 0 else ""
        tags = "".join('<span>%s</span>' % esc(t) for t in l["tags"])
        rows.append(
            '        <button class="ix__layer%s" data-ix-layer="%d" type="button">\n'
            '          <span class="ix__layer-t">%s</span>\n'
            '          <span class="ix__layer-d">%s</span>\n'
            '          <span class="ix__layer-tags">%s</span>\n        </button>'
            % (on, i, esc(l["t"]), esc(l["d"]), tags))
    return '      <div class="ix__layers">\n%s\n      </div>' % "\n".join(rows)


def ix_transcript(ix):
    rows = []
    for i, t in enumerate(ix["turns"]):
        rows.append('        <div class="ix__turn ix__turn--%s" data-ix-turn="%d">%s</div>'
                    % (t["who"], i, esc(t["text"])))
    return ('      <div class="ix__log" data-ix-log>\n%s\n      </div>\n'
            '      <div class="ix__ctl">\n'
            '        <button class="btn btn--sm" data-ix-play type="button"><span>Play it back</span></button>\n'
            '        <button class="btn btn--ghost btn--sm" data-ix-reset type="button"><span>Reset</span></button>\n'
            '      </div>' % "\n".join(rows))


RENDERERS = {"flow": ix_flow, "screens": ix_screens, "metrics": ix_metrics,
             "stack": ix_stack, "transcript": ix_transcript}


def render_ix(ix):
    if not ix:
        return ""
    inner = RENDERERS[ix["type"]](ix)
    return """
<section class="section section--tight">
  <div class="wrap">
    <div class="ix" data-ix="{kind}" data-anim="up">
      <div class="ix__head">
        <span class="badge">{label}</span>
        <h2 class="d3">{title}</h2>
      </div>
{inner}
    </div>
  </div>
</section>
""".format(kind=ix["type"], label=esc(ix["label"]), title=esc(ix["title"]), inner=inner)


# ──────────────────────────────── page render ────────────────────────────────

def jsonld(p, url):
    return """{
  "@context": "https://schema.org",
  "@type": "CreativeWork",
  "name": "%s",
  "headline": "%s",
  "url": "%s",
  "image": "%s/%s/%s",
  "about": "%s",
  "creator": {
    "@type": "Organization",
    "name": "Alpha Squared",
    "url": "%s/",
    "address": {
      "@type": "PostalAddress",
      "addressLocality": "Edmonton",
      "addressRegion": "AB",
      "addressCountry": "CA"
    }
  }
}""" % (attr(p["name"]), attr(p["tagline"]), url, SITE, IMG_HREF, p["images"][0][0],
        attr(p["category"]), SITE)


def page_title(p):
    """Search results truncate around 65 characters, so drop the tagline
    rather than ship a title nobody sees the end of."""
    if p["title"]:
        return p["title"]
    suffix = " | Alpha Squared"
    full = "%s: %s%s" % (p["name"], p["tagline"].rstrip("."), suffix)
    if len(full) <= 65:
        return full
    short = "%s Case Study%s" % (p["name"], suffix)
    return short if len(short) <= 65 else p["name"] + suffix


# ───────────────────────── domain automation strip ───────────────────────────
# The four hops the system makes without anyone retyping anything, written per
# domain. First keyword that matches the project's category wins, so the order
# here matters: put the specific families above the generic ones.

DOMAINS = [
    (("trucking", "transport"), "truck",
     ["Load created", "Driver accepts", "Proof captured", "Invoice sent"]),
    (("healthcare",), "health",
     ["Patient checks in", "Record updated", "Plan issued", "Follow-up booked"]),
    (("energy", "industrial"), "chart",
     ["Sample logged", "Data parsed", "Model runs", "Report published"]),
    (("ai in production",), "wave",
     ["Call answered", "Intent read", "Slot booked", "CRM updated"]),
    (("govtech", "public safety"), "shield",
     ["Event detected", "Case opened", "Evidence filed", "Unit dispatched"]),
    (("cybersecurity",), "shield",
     ["Asset scanned", "Risk scored", "Alert raised", "Fix verified"]),
    (("fintech",), "coin",
     ["Request raised", "Checks run", "Payment cleared", "Ledger updated"]),
    (("food delivery",), "bag",
     ["Order placed", "Kitchen notified", "Driver assigned", "Delivery confirmed"]),
    (("e-commerce", "pos", "erp"), "bag",
     ["Order placed", "Stock checked", "Payment taken", "Shipment tracked"]),
    (("iptv", "streaming", "media"), "play",
     ["Catalog synced", "Stream requested", "Playback starts", "Watchlist saved"]),
    (("travel", "tourism", "hospitality"), "pin",
     ["Search made", "Availability checked", "Booking held", "Confirmation sent"]),
    (("sports", "fitness"), "chart",
     ["Schedule set", "Squad notified", "Result recorded", "Table updated"]),
    (("legal",), "doc",
     ["Draft prepared", "Clauses checked", "Signature captured", "Archive indexed"]),
    (("training", "simulation"), "play",
     ["Scenario loaded", "Session runs", "Errors scored", "Result issued"]),
    (("real estate",), "pin",
     ["Listing added", "Lead captured", "Viewing booked", "Offer tracked"]),
    (("enterprise", "internal tools"), "grid",
     ["Request submitted", "Routed by hierarchy", "Actioned", "Logged"]),
    (("nonprofit", "social good", "charity"), "coin",
     ["Donation made", "Receipt issued", "Funds allocated", "Impact reported"]),
    (("marketing site",), "grid",
     ["Visitor lands", "Intent captured", "Lead routed", "Follow-up sent"]),
    (("marketplace", "childcare", "beauty"), "grid",
     ["Request posted", "Provider matched", "Booking confirmed", "Payment released"]),
    (("social", "community", "dating", "networking", "productivity"), "wave",
     ["Activity captured", "Rules applied", "People notified", "History kept"]),
]

DOMAIN_FALLBACK = ("grid", ["Data captured", "Rules applied", "Action taken", "Record kept"])

ICONS = {
    "truck": '<path d="M2.5 6.5h10v9h-10z"/><path d="M12.5 9.5h4l3 3v3h-7z"/>'
             '<circle cx="7" cy="17.5" r="1.9"/><circle cx="16.5" cy="17.5" r="1.9"/>',
    "health": '<path d="M12 20.5S3.5 15.6 3.5 9.9A4.4 4.4 0 0 1 12 8a4.4 4.4 0 0 1 8.5 1.9'
              'c0 5.7-8.5 10.6-8.5 10.6Z"/><path d="M12 10.4v4M10 12.4h4"/>',
    "chart": '<path d="M3.5 20.5h17"/><path d="M6.5 20.5V12M11 20.5V6.5M15.5 20.5v-5M20 20.5V9"/>',
    "wave": '<path d="M2.8 12.4h3l2.2 6 4-15 2.8 9h6.4"/>',
    "shield": '<path d="M12 2.6 4.5 5.8v6c0 4.6 3.2 8.4 7.5 9.6 4.3-1.2 7.5-5 7.5-9.6v-6Z"/>'
              '<path d="M9 12l2.1 2.1L15.4 9.6"/>',
    "coin": '<circle cx="12" cy="12" r="8.5"/><path d="M12 7.2v9.6M14.6 9.4a3 3 0 0 0-5 2.2'
            'c0 2.9 5 1.4 5 4a3 3 0 0 1-5 2.1"/>',
    "bag": '<path d="M4.5 7.5h15l-1.2 12h-12.6z"/><path d="M8.8 7.5V5.8a3.2 3.2 0 0 1 6.4 0v1.7"/>',
    "play": '<rect x="2.5" y="4.5" width="19" height="15" rx="2"/><path d="M10 9.2 15 12l-5 2.8Z"/>',
    "pin": '<path d="M12 21s7-5.6 7-11a7 7 0 1 0-14 0c0 5.4 7 11 7 11Z"/><circle cx="12" cy="10" r="2.6"/>',
    "doc": '<path d="M6 3.5h8l4 4v13H6z"/><path d="M14 3.5v4h4M9 12.5h6M9 16h4"/>',
    "grid": '<rect x="3.2" y="3.2" width="7.4" height="7.4" rx="1.6"/>'
            '<rect x="13.4" y="3.2" width="7.4" height="7.4" rx="1.6"/>'
            '<rect x="3.2" y="13.4" width="7.4" height="7.4" rx="1.6"/>'
            '<rect x="13.4" y="13.4" width="7.4" height="7.4" rx="1.6"/>',
}


def domain_of(category):
    key = category.lower()
    for words, icon, steps in DOMAINS:
        if any(w in key for w in words):
            return icon, steps
    return DOMAIN_FALLBACK


def render_domflow(p):
    icon, steps = domain_of(p["category"])
    cells = "\n".join(
        '          <li style="--i:%d"><b>%02d</b><span>%s</span></li>' % (i, i + 1, esc(s))
        for i, s in enumerate(steps))
    return """      <div class="domflow" data-anim="up">
        <div class="domflow__head">
          <span class="domflow__i" aria-hidden="true"><svg viewBox="0 0 24 24">%s</svg></span>
          <div>
            <span class="domflow__k">%s &middot; running unattended</span>
            <p class="domflow__t">What the system does without anyone retyping it</p>
          </div>
        </div>
        <ol class="domflow__steps">
%s
        </ol>
      </div>""" % (ICONS[icon], esc(p["category"]), cells)


# The three hand-authored pages skip render_page(), so syncsite.py installs
# this same band into them.
INTRO = """<section class="section section--tight">
  <div class="wrap">
    <nav class="pager pager--top" aria-label="Case study navigation">
      <a class="pager__side" href="{prev_slug}.html">
        <span class="pager__k">Previous</span>
        <span class="pager__t">{prev_name}</span>
      </a>
      <a class="pager__mid" href="../case-studies.html">All 48 case studies</a>
      <a class="pager__side pager__side--next" href="{next_slug}.html">
        <span class="pager__k">Next</span>
        <span class="pager__t">{next_name}</span>
      </a>
    </nav>

{domflow}
  </div>
</section>"""


def render_intro(p, prev_p, next_p):
    return INTRO.format(prev_slug=prev_p["slug"], prev_name=esc(prev_p["name"]),
                        next_slug=next_p["slug"], next_name=esc(next_p["name"]),
                        domflow=render_domflow(p))



def render_page(p, prev_p, next_p):
    url = "%s/case-studies/%s.html" % (SITE, p["slug"])
    title = page_title(p)
    desc = p["description"] or p["card"]
    hero_img, hero_alt = p["images"][0]

    head = HEAD.format(title=attr(title), description=attr(desc), url=url,
                       ogimage="%s/%s/%s" % (SITE, IMG_HREF, hero_img),
                       jsonld=jsonld(p, url))

    chips = "".join("<span>%s</span>" % esc(c) for c in p["chips"])
    shipped = "\n".join("            <li>%s</li>" % esc(s) for s in p["shipped"])
    today = "\n".join("            <li>%s</li>" % esc(s) for s in p["today"])

    body = """
<section class="hero hero--page hero--case">
  <div class="hero__arc" data-parallax="0.12"></div>
  <div class="hero__bloom" data-parallax="0.2"></div>

  <div class="wrap hero__inner">
    <nav class="crumbs" aria-label="Breadcrumb">
      <a href="../index.html">Home</a> <span aria-hidden="true">/</span>
      <a href="../case-studies.html">Case Studies</a> <span aria-hidden="true">/</span>
      <span aria-current="page">{name}</span>
    </nav>
    <span class="hero__eyebrow grad" data-anim="fade">{category}</span>
    <h1 class="d1" data-split="words">{name}</h1>
    <p class="hero__sub" data-anim="fade" data-delay="0.4">{tagline}</p>
  </div>
</section>

{intro}

<section class="section">
  <div class="wrap">
    <div class="study" data-anim="up">
      <div class="study__top">
        <div>
          <span class="badge">{category}</span>
          <h2 class="d3" style="margin-top:16px">What it is</h2>
          <p class="lead" style="margin-top:14px">{lead}</p>
          <div class="chips">{chips}</div>
        </div>
        <figure class="study__shot">
          <img src="../{img_href}/{hero_img}" alt="{hero_alt}" loading="lazy" decoding="async" />
        </figure>
      </div>

      <div class="study__grid">
        <div>
          <h3>The problem</h3>
          <p>{problem}</p>
        </div>
        <div>
          <h3>What we shipped</h3>
          <ul class="ticks">
{shipped}
          </ul>
        </div>
        <div>
          <h3>Where it stands today</h3>
          <ul class="ticks">
{today}
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
{ix}
<div class="page-light">
  <section class="section section--tight">
    <div class="wrap">
      <nav class="pager" aria-label="More case studies">
        <a class="pager__side" href="{prev_slug}.html">
          <span class="pager__k">Previous</span>
          <span class="pager__t">{prev_name}</span>
        </a>
        <a class="pager__mid" href="../case-studies.html">All 48 case studies</a>
        <a class="pager__side pager__side--next" href="{next_slug}.html">
          <span class="pager__k">Next</span>
          <span class="pager__t">{next_name}</span>
        </a>
      </nav>
    </div>
  </section>

  <section class="final final--close" id="contact">
    <div class="wrap">
      <div class="close" data-anim="up">
        <h2 class="d2" data-anim="up">Show Us One Manual Process. <em>We'll Show You What Automating It Takes</em></h2>
        <p class="lead">One conversation, and you know what it takes.</p>

        <div class="close__act">
          <a class="btn" href="https://wa.me/18259772020?text=Hi%20Alpha%20Squared%2C%20I%27d%20like%20to%20book%20a%20call%20about%20a%20build."
             target="_blank" rel="noopener">
            <span>Book a call <i class="ar">&rarr;</i></span>
          </a>

          <a class="btn btn--ghost" href="../contact.html"><span>Send a brief</span></a>
        </div>
      </div>
    </div>
  </section>
</div>
""".format(name=esc(p["name"]), category=esc(p["category"]), tagline=esc(p["tagline"]),
           lead=esc(p["lead"]), chips=chips, img_href=IMG_HREF, hero_img=hero_img,
           hero_alt=attr(hero_alt), problem=esc(p["problem"]), shipped=shipped,
           today=today, ix=render_ix(p["ix"]), intro=render_intro(p, prev_p, next_p),
           prev_slug=prev_p["slug"], prev_name=esc(prev_p["name"]),
           next_slug=next_p["slug"], next_name=esc(next_p["name"]))

    return head + body + FOOT.format(chatbot=CHATBOT)


# ─────────────────────────────── index grid ──────────────────────────────────

CARD = """      <article class="work" data-anim="up"{delay}>
        <a class="work__link" href="case-studies/{slug}.html">
          <div class="work__shot">
            <img src="{href}/{image}" alt="{alt}" loading="lazy" decoding="async" />
          </div>
          <div class="work__body">
            <span class="badge">{category}</span>
            <h3>{name}</h3>
            <p>{desc}</p>
            <span class="tlink">Read the case study <i class="ar">&rarr;</i></span>
          </div>
        </a>
      </article>"""


def render_grid(projects):
    cards = []
    for i, p in enumerate(projects):
        column = i % 3
        cards.append(CARD.format(
            delay="" if column == 0 else ' data-delay="%.2f"' % (0.08 * column),
            slug=p["slug"], href=IMG_HREF, image=p["images"][0][0],
            alt=attr(p["images"][0][1]), category=esc(p["category"]),
            name=esc(p["name"]), desc=esc(p["card"])))
    return "\n\n".join(cards)


# ──────────────────────────────── sitemap ────────────────────────────────────

def render_sitemap(projects):
    today = datetime.date.today().isoformat()
    urls = []
    for page, priority in STATIC_PAGES:
        loc = "%s/" % SITE if page == "index.html" else "%s/%s" % (SITE, page)
        urls.append("  <url>\n    <loc>%s</loc>\n    <lastmod>%s</lastmod>\n"
                    "    <changefreq>monthly</changefreq>\n    <priority>%s</priority>\n  </url>"
                    % (loc, today, priority))
    for p in projects:
        urls.append("  <url>\n    <loc>%s/case-studies/%s.html</loc>\n    <lastmod>%s</lastmod>\n"
                    "    <changefreq>yearly</changefreq>\n    <priority>0.7</priority>\n  </url>"
                    % (SITE, p["slug"], today))
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(urls) + "\n</urlset>\n")


# ──────────────────────────────────── main ───────────────────────────────────

def load_projects():
    """casedata.PROJECTS, or the JSON export when --from-json is passed."""
    if "--from-json" not in sys.argv:
        return casedata.PROJECTS, casedata.FLAGSHIP

    if not os.path.exists(EXPORT):
        raise SystemExit("missing %s; run 'python exportcases.py' first" % EXPORT)

    with open(EXPORT, encoding="utf-8") as fh:
        records = json.load(fh)

    records = [r for r in records if r.get("published", True)]
    records.sort(key=lambda r: r.get("order", 0))
    for r in records:
        # JSON has no tuples, and the templates unpack (file, alt).
        r["images"] = [tuple(img) for img in r["images"]]

    flagship = tuple(r["slug"] for r in records if r.get("flagship"))
    return records, flagship


def main():
    projects, flagship = load_projects()
    for p in projects:
        missing = [f for f, _ in p["images"] if not os.path.exists(os.path.join(IMG_DIR, f))]
        if missing:
            raise SystemExit("%s references missing images: %s" % (p["slug"], missing))

    if not os.path.isdir(OUT_DIR):
        os.makedirs(OUT_DIR)

    written = 0
    for i, p in enumerate(projects):
        if p["hand"]:
            continue
        prev_p = projects[i - 1]
        next_p = projects[(i + 1) % len(projects)]
        path = os.path.join(OUT_DIR, "%s.html" % p["slug"])
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(render_page(p, prev_p, next_p))
        written += 1

    grid = [p for p in projects if p["slug"] not in flagship]
    with open(INDEX, encoding="utf-8") as fh:
        page = fh.read()
    if START not in page or END not in page:
        raise SystemExit("work markers not found in case-studies.html")
    block = "%s\n%s\n      %s" % (START, render_grid(grid), END)
    page = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, page, flags=re.S)
    with open(INDEX, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(page)

    with open(SITEMAP, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_sitemap(projects))

    print("generated %d detail pages, %d index cards, %d sitemap URLs"
          % (written, len(grid), len(projects) + len(STATIC_PAGES)))


if __name__ == "__main__":
    main()
